### ISSUE TITLE
Docker Hub: support arm64 builds

### ISSUE THREAD

**Issue by shumvgolove** [simplex-chat/simplexmq#740]
Currently, [Docker workflow](https://github.com/simplex-chat/simplexmq/blob/stable/.github/workflows/docker-image.yml) supports building and pushing only `amd64` images to Docker Hub, since compiling `arm64` binaries with `qemu`/`docker` [results in OOM](https://github.com/simplex-chat/simplexmq/pull/734#issuecomment-1521508025), even on powerful machines with 32Gb RAM. Let's figure out the best way to support `arm64`.

Currently, proposed solutions:

- Integrate with [CircleCI](https://circleci.com) workflow
  - Requires separate workflow, not compatible with GitHub actions.
  - Requires 3 CI jobs: two for creating `amd64` and `arm64` respectfully and one for combining this images into manifest.
     Source: [Multi-Arch Build With Docker Buildx and CircleCi](https://behroozam.medium.com/multi-arch-build-with-docker-buildx-and-circleci-900eb3827274)
  - Simplex Chat need to apply for free tier plan for Open Source projects.
- Selfhost Github runner on `aarch64` hardware.
  - Need to figure out where to host `arm` server.
  - Set up Github runner (pretty straightforward).
  - Adjust [`docker-image.yml`](https://github.com/simplex-chat/simplexmq/blob/stable/.github/workflows/docker-image.yml)

**Comment by samsapti** [comment]
Just to add to this: [CircleCI has native ARM support](https://circleci.com/docs/using-arm/), which is why it's expected to work.

If the self-hosted GitHub Actions runner solution is chosen, you still need three CI jobs, just like with CircleCI, and run the `arm64` build on the self-hosted runner.

**Comment by shumvgolove** [comment]
> you still need three CI jobs ... because the arm64 build needs to run on the self-hosted runner while the others run on the GitHub-hosted runners

So we can not specify something like:

```yml

jobs:
  build-and-push:
    name: Build and push Docker image
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - application: smp-server
            dockerfile: build.Dockerfile
          - os: [ubuntu-latest, self-hosted]
    ...
```

… to build all the images to one manifest on separate runners automagically?

**Comment by samsapti** [comment]
Actually yes, you coudl do something like that. Then you would only need two jobs, one with a matrix to build the images, and one for making the manifest. You could also use some Bash magic to get the architecture for the image tags, like so

```yaml
...
jobs:
  build-and-push-images:
    name: Build and push Docker image
    strategy:
      fail-fast: false
      matrix:
        application: smp-server
        dockerfile: build.Dockerfile
        os: [ubuntu-latest, self-hosted]
    runs-on: ${{ matrix.os }}
    steps:
...
      - name: Get machine architecture for image tags
        id: arch
        run: |
          if [ "$(uname -m)" = "x86_64" ]; then
              echo "tag=amd64" >> "$GITHUB_OUTPUT"
          elif [ "$(uname -m)" = "aarch64" ]; then
              echo "tag=arm64" >> "$GITHUB_OUTPUT"
          fi

      - name: Extract metadata for Docker image
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.application }}
          flavor: |
            latest=auto
            suffix=-${{ steps.arch.output.tag }},onlatest=true
          tags: |
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}
...
  create-and-push-manifest:
    name: Create and push Docker manifest
...
```
