### ISSUE TITLE
SMP or XFTP server address avoiding it ends with the port number

### ISSUE THREAD

**Issue by nicfab** [simplex-chat/simplexmq#769]
I had to set up SMP and XFTP servers on a different port instead of the default ones because the default (especially 443 is already taken by another service).
Thus, the server (SMP or XFTP) address finishes with `@domain:portnumber`.
Is there any way to avoid the server address finishing as mentioned below, with `@domain:portnumber`?
I mean, modifying some parameters somewhere.

**Comment by Death-Pact** [comment]
I would also love to see the ability to change ports. 443 is very commonly reverse proxies for many.

**Comment by seb81** [comment]
If you are using docker compose, just specify:

```
version: "3"
services:
  simplexchat-xftp:
    ...
    ports:
      - "5233:443"
    ...
```
and add this portnumber=5233
@domain:5233
