### ISSUE TITLE
[Docker] Trying to set up SimpleXFTPServer

### ISSUE THREAD

**Issue by kokomo123** [simplex-chat/simplexmq#779]
Hi there, i've been having problems with the server not initializing the config file properly while using it in a docker compose. 
My OS: Debian GNU/Linux 12 (bookworm) x86_64 6.1.0-9-cloud-amd64 
Docker Version: 24.0.2 with docker compose version v2.18.1
I've been getting the output ``SimpleX XFTP server v1.0.0
Fingerprint: [RETRACTED]
xftp-server: no key port in section TRANSPORT
CallStack (from HasCallStack):
  error, called at src/Simplex/Messaging/Server/CLI.hs:161:14 in simplexmq-5.1.1-inplace:Simplex.Messaging.Server.CLI
``
My full docker-compose is 
```yaml 
version: '3.3'
services:
    smp-server:
        restart: unless-stopped
        environment:
            - ADDR=[RETRACTED]
            - PASS=[RETRACTED]
        ports:
            - '5223:5223'
        volumes:
            - '$HOME/simplex/smp/config:/etc/opt/simplex'
            - '$HOME/simplex/smp/logs:/var/opt/simplex'
        image: 'simplexchat/smp-server:latest'

    xftp-server:
        restart: unless-stopped
        environment:
            - ADDR=[RETRACTED]
            - QUOTA=10GB
        ports:
            - '443:443'
        volumes:
            - '$HOME/simplex/xftp/config:/etc/opt/simplex-xftp'
            - '$HOME/simplex/xftp/logs:/var/opt/simplex-xftp'
            - '$HOME/simplex/xftp/files:/srv/xftp'
        image: 'simplexchat/xftp-server:latest'
```
Any thoughts?
