### ISSUE TITLE
Help Running on Oracle Cloud Free Tier

### ISSUE THREAD

**Issue by tootbrute** [simplex-chat/simplexmq#812]
I can't get it running on Oracle Cloud Free Tier on Debian 11. Also a few questions about how to deploy.

1. I setup with docker-compose. I changed XFTP server to port 5224. I left localhost in here but used my domain name when trying to use them in SimpleX android app.

```
version: '3.3'
services:
    smp-server:
        environment:
            - ADDR=localhost
#            - PASS=password
        ports:
            - '5223:5223'
        volumes:
            - '$HOME/simplex/smp/config:/etc/opt/simplex:z'
            - '$HOME/simplex/smp/logs:/var/opt/simplex:z'
        image: 'simplexchat/smp-server:latest'

    xftp-server:
        environment:
            - ADDR=localhost
            - QUOTA=1048576
        ports:
            - '5224:443'
        volumes:
            - '$HOME/simplex/xftp/config:/etc/opt/simplex-xftp:z'
            - '$HOME/simplex/xftp/logs:/var/opt/simplex-xftp:z'
```
3. For XFTP is quota in MBs or KBs?
4. Do you need to run this behind a reverse proxy? or open ports?
5. I tried running them behind Caddy but didn't work in SimpleX. I tried SMP server with just an open port and SimpleX app gave me a red X.
